package javaswingdev.form;

import com.bike.common.MD5;
import com.bike.common.SystemConfigData;
import com.bike.db.DB;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.log4j.Logger;

public class BasiCSalary extends javax.swing.JPanel {

    private Logger log;

    public BasiCSalary() {
        initComponents();
        log = Logger.getLogger("bikeLogger");
        log.info("Manage Basic Salary Page Loaded");
        table.fixTable(jScrollPane1);
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new javaswingdev.swing.RoundPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_salary = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_selectEmp = new javax.swing.JButton();
        update = new javax.swing.JButton();
        clearField = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_role = new javax.swing.JTextField();
        save1 = new javax.swing.JButton();
        txt_emp_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_emp_name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        card2 = new javaswingdev.card.Card();
        jLabel14 = new javax.swing.JLabel();
        switchButton = new javaswingdev.swing.SwitchButton();
        jLabel11 = new javax.swing.JLabel();
        roundPanel2 = new javaswingdev.swing.RoundPanel();
        card1 = new javaswingdev.card.Card();
        jLabel13 = new javax.swing.JLabel();
        textFieldAnimation1 = new swing.TextFieldAnimation();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javaswingdev.swing.table.Table();

        setBackground(new java.awt.Color(228, 232, 229));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Manage Basic Salary");
        roundPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        txt_salary.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_salary.setForeground(new java.awt.Color(102, 102, 102));
        txt_salary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_salary.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        txt_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_salaryActionPerformed(evt);
            }
        });
        txt_salary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_salaryKeyTyped(evt);
            }
        });
        roundPanel1.add(txt_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 340, 35));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Basic Salary - LKR");
        roundPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        btn_selectEmp.setBackground(new java.awt.Color(153, 204, 255));
        btn_selectEmp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btn_selectEmp.setForeground(new java.awt.Color(0, 102, 204));
        btn_selectEmp.setText("SELECT EMPLOYEE");
        btn_selectEmp.setBorder(null);
        btn_selectEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectEmpActionPerformed(evt);
            }
        });
        roundPanel1.add(btn_selectEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 340, 35));

        update.setBackground(new java.awt.Color(153, 204, 255));
        update.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        update.setForeground(new java.awt.Color(0, 102, 204));
        update.setText("UPDATE");
        update.setBorder(null);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        roundPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 820, 160, 35));

        clearField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/burger/icon/close_1.png"))); // NOI18N
        clearField.setText("Clear Fields");
        clearField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearFieldMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearFieldMouseEntered(evt);
            }
        });
        roundPanel1.add(clearField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 820, 120, 40));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Job Role");
        roundPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        txt_role.setEditable(false);
        txt_role.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_role.setForeground(new java.awt.Color(102, 102, 102));
        txt_role.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_role.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        txt_role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_roleActionPerformed(evt);
            }
        });
        roundPanel1.add(txt_role, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 340, 35));

        save1.setBackground(new java.awt.Color(153, 204, 255));
        save1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        save1.setForeground(new java.awt.Color(0, 102, 204));
        save1.setText("SAVE USER");
        save1.setBorder(null);
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        roundPanel1.add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 760, 340, 35));

        txt_emp_id.setEditable(false);
        txt_emp_id.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_emp_id.setForeground(new java.awt.Color(102, 102, 102));
        txt_emp_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_emp_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        txt_emp_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emp_idActionPerformed(evt);
            }
        });
        roundPanel1.add(txt_emp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 340, 35));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Employee ID");
        roundPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txt_emp_name.setEditable(false);
        txt_emp_name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_emp_name.setForeground(new java.awt.Color(102, 102, 102));
        txt_emp_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_emp_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        txt_emp_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emp_nameActionPerformed(evt);
            }
        });
        roundPanel1.add(txt_emp_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 340, 35));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Employee Name");
        roundPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        card2.setDescription("");
        card2.setIcon(javaswingdev.GoogleMaterialDesignIcon.PLAYLIST_ADD);
        roundPanel1.add(card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 60, 50));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setText("Add");
        roundPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        switchButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        switchButton.setName(""); // NOI18N
        roundPanel1.add(switchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, 40, 20));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Status");
        roundPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, -1, -1));

        add(roundPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 1030));

        roundPanel2.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        card1.setDescription("");
        card1.setIcon(javaswingdev.GoogleMaterialDesignIcon.SEARCH);
        roundPanel2.add(card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 50));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("Search Employee");
        roundPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        textFieldAnimation1.setBackground(new java.awt.Color(228, 232, 229));
        textFieldAnimation1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldAnimation1KeyReleased(evt);
            }
        });
        roundPanel2.add(textFieldAnimation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 330, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Basic Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        roundPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 200, 1230, 800));

        add(roundPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 1280, 1030));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_selectEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selectEmpActionPerformed
        PopUpEmp emp = new PopUpEmp(BasiCSalary.this);
        emp.setVisible(true);
        txt_salary.grabFocus();


    }//GEN-LAST:event_btn_selectEmpActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {

            if (!txt_emp_id.getText().equals("") && !txt_salary.getText().equals("")) {
                ResultSet rs = DB.search("select * from basic_salary where emp_id ='" + txt_emp_id.getText() + "' ");
                if (rs.next()) {

                    String stat = "none";

                    String status = null;
                    if (switchButton.isSelected()) {
                        status = "1";
                    } else {
                        status = "0";
                    }

                    DB.push("update basic_salary set  basic_salary='" + txt_salary.getText() + "'"
                            + ", stat='" + stat + "',status='" + status + "' where emp_id ='"
                            + txt_emp_id.getText() + "' ");

                    DB.push("insert into system_activity (detail, date, time, employee) values ("
                            + "'Basic salary Update',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'" + SystemConfigData.getEmployee() + "')");

                    log.info("Basic Salary Update Successful. Employee : " + txt_emp_id.getText() + " | By : " + SystemConfigData.getEmployee());
                    clearFields();
                    JOptionPane.showMessageDialog(this, "Basic Salary Updated!!", "Saved", JOptionPane.INFORMATION_MESSAGE);
                    loadTable();

                } else {
                    JOptionPane.showMessageDialog(this, "Please use SAVE button to new Employee", "Error", JOptionPane.ERROR_MESSAGE);

                }
            } else {
                JOptionPane.showMessageDialog(this, "Please Enter Salary!", "Error", JOptionPane.ERROR_MESSAGE);

            }
        } catch (Exception e) {
            log.error("Salary Update Failed", e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        try {
            DefaultTableModel dtm = (DefaultTableModel) table.getModel();
            int selectRow = table.getSelectedRow();

            String emp_id = dtm.getValueAt(selectRow, 0).toString();
            txt_emp_id.setText(emp_id);
            String salary = dtm.getValueAt(selectRow, 1).toString();
            txt_salary.setText(salary);
            
             ResultSet rs3 = DB.search("select * from basic_salary where emp_id = '" + emp_id + "'");
            if (rs3.next()) {
                String status = (rs3.getString("status"));
                 if (status.equals("1")) {
                    switchButton.setSelected(true);
                } else {
                    switchButton.setSelected(false);
                }
                

            }

            ResultSet rs = DB.search("select * from employee where emp_id = '" + emp_id + "'");
            if (rs.next()) {
                txt_emp_name.setText(rs.getString("fname") + " " + rs.getString("lname"));

            }
            String roleID = (rs.getString("role_id"));
            ResultSet rs2 = DB.search("select * from role where role_id = '" + roleID + "'");
            if (rs2.next()) {
                String role = (rs2.getString("role"));
                txt_role.setText(role);

            }

        } catch (Exception e) {
            log.error("Load Employee Details Failed", e);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void clearFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearFieldMouseClicked
        clearFields();
    }//GEN-LAST:event_clearFieldMouseClicked

    private void clearFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearFieldMouseEntered

    }//GEN-LAST:event_clearFieldMouseEntered

    private void textFieldAnimation1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldAnimation1KeyReleased
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        String searchText = textFieldAnimation1.getText();
        TableRowSorter<DefaultTableModel> searchUser = new TableRowSorter<>(dtm);
        table.setRowSorter(searchUser);
        searchUser.setRowFilter(RowFilter.regexFilter(searchText));
    }//GEN-LAST:event_textFieldAnimation1KeyReleased

    private void txt_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_salaryActionPerformed

    }//GEN-LAST:event_txt_salaryActionPerformed

    private void txt_roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_roleActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
        try {
            ResultSet rs = DB.search("select * from basic_salary where emp_id ='" + txt_emp_id.getText() + "' ");
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Salary is already Added.Please use UPDATE button to update details", "Error", JOptionPane.ERROR_MESSAGE);

            } else {
                if (!txt_emp_id.getText().equals("") && !txt_salary.getText().equals("")) {

                    String stat = "none";

                    String status = null;
                    if (switchButton.isSelected()) {
                        status = "1";
                    } else {
                        status = "0";
                    }

                    DB.push("insert into basic_salary values('"
                            + txt_emp_id.getText() + "','"
                            + txt_salary.getText() + "','"
                            + stat + "','"
                            + status + "')");

                    DB.push("insert into system_activity (detail, date, time, employee) values ("
                            + "'Basic salary Saved',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),'" + SystemConfigData.getEmployee() + "')");

                    log.info("Basic Salary Saved Successful. Employee : " + txt_emp_id.getText() + " | By : " + SystemConfigData.getEmployee());
                    clearFields();
                    JOptionPane.showMessageDialog(this, "Basic Salary Added!!", "Saved", JOptionPane.INFORMATION_MESSAGE);
                    loadTable();

                } else {
                    JOptionPane.showMessageDialog(this, "Please Enter Salary!", "Error", JOptionPane.ERROR_MESSAGE);

                }
            }
        } catch (Exception e) {
            log.error("Salary Save Failed", e);
        }
    }//GEN-LAST:event_save1ActionPerformed

    private void txt_emp_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emp_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emp_idActionPerformed

    private void txt_emp_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emp_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emp_nameActionPerformed

    private void txt_salaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_salaryKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_salaryKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_selectEmp;
    private javaswingdev.card.Card card1;
    private javaswingdev.card.Card card2;
    private javax.swing.JLabel clearField;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javaswingdev.swing.RoundPanel roundPanel1;
    private javaswingdev.swing.RoundPanel roundPanel2;
    private javax.swing.JButton save1;
    private javaswingdev.swing.SwitchButton switchButton;
    private javaswingdev.swing.table.Table table;
    private swing.TextFieldAnimation textFieldAnimation1;
    public javax.swing.JTextField txt_emp_id;
    public javax.swing.JTextField txt_emp_name;
    public javax.swing.JTextField txt_role;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        txt_emp_id.setText(null);
        txt_emp_name.setText(null);
        txt_role.setText(null);
        txt_salary.setText(null);
        switchButton.setSelected(false);

    }

    private void loadTable() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) table.getModel();
            dtm.setRowCount(0);
            ResultSet rs = DB.search("select * from basic_salary");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("emp_id"));
                v.add(rs.getString("basic_salary"));
                dtm.addRow(v);
            }

        } catch (Exception e) {
            log.error("Load Basic salary Details Failed", e);
        }
    }
}
