package javaswingdev.form;

import com.bike.db.DB;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.log4j.Logger;

public class ServiceDetails extends javax.swing.JPanel {

    private Logger log;

    public ServiceDetails() {
        initComponents();
        log = Logger.getLogger("bikeLogger");
        log.info("Service Details Page Loaded");
        JT_service.fixTable(jScrollPane1);
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new javaswingdev.swing.RoundPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_serv_id = new javax.swing.JTextField();
        txt_bike_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_customer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_amount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_mechanicID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_service_type = new javax.swing.JTextField();
        txt_mechanic_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        clearField = new javax.swing.JLabel();
        roundPanel2 = new javaswingdev.swing.RoundPanel();
        card1 = new javaswingdev.card.Card();
        jLabel13 = new javax.swing.JLabel();
        textFieldAnimation1 = new swing.TextFieldAnimation();
        jScrollPane1 = new javax.swing.JScrollPane();
        JT_service = new javaswingdev.swing.table.Table();

        setBackground(new java.awt.Color(228, 232, 229));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Service Details");
        roundPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Service ID");
        roundPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txt_serv_id.setEditable(false);
        txt_serv_id.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_serv_id.setForeground(new java.awt.Color(102, 102, 102));
        txt_serv_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_serv_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        roundPanel1.add(txt_serv_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 340, 35));

        txt_bike_id.setEditable(false);
        txt_bike_id.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_bike_id.setForeground(new java.awt.Color(102, 102, 102));
        txt_bike_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_bike_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        roundPanel1.add(txt_bike_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 340, 35));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Bike ID");
        roundPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txt_customer.setEditable(false);
        txt_customer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_customer.setForeground(new java.awt.Color(102, 102, 102));
        txt_customer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_customer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        roundPanel1.add(txt_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 340, 35));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Mechanic ID");
        roundPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, -1, -1));

        txt_amount.setEditable(false);
        txt_amount.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_amount.setForeground(new java.awt.Color(102, 102, 102));
        txt_amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_amount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        roundPanel1.add(txt_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 340, 35));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Service Type");
        roundPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        txt_date.setEditable(false);
        txt_date.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_date.setForeground(new java.awt.Color(102, 102, 102));
        txt_date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        roundPanel1.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 340, 35));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Service Amount");
        roundPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        txt_mechanicID.setEditable(false);
        txt_mechanicID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_mechanicID.setForeground(new java.awt.Color(102, 102, 102));
        txt_mechanicID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_mechanicID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        roundPanel1.add(txt_mechanicID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 340, 35));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Service Date");
        roundPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Customer ID");
        roundPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        txt_service_type.setEditable(false);
        txt_service_type.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_service_type.setForeground(new java.awt.Color(102, 102, 102));
        txt_service_type.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_service_type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        roundPanel1.add(txt_service_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 340, 35));

        txt_mechanic_name.setEditable(false);
        txt_mechanic_name.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_mechanic_name.setForeground(new java.awt.Color(102, 102, 102));
        txt_mechanic_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_mechanic_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));
        roundPanel1.add(txt_mechanic_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 760, 340, 35));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Mechanic Name");
        roundPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, -1, -1));

        clearField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/burger/icon/close_1.png"))); // NOI18N
        clearField.setText("Clear Fields");
        clearField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearFieldMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearFieldMouseEntered(evt);
            }
        });
        roundPanel1.add(clearField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 900, 120, 40));

        add(roundPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 1030));

        roundPanel2.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        card1.setDescription("");
        card1.setIcon(javaswingdev.GoogleMaterialDesignIcon.SEARCH);
        roundPanel2.add(card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 50));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setText("Search Service");
        roundPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        textFieldAnimation1.setBackground(new java.awt.Color(228, 232, 229));
        textFieldAnimation1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldAnimation1KeyReleased(evt);
            }
        });
        roundPanel2.add(textFieldAnimation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 330, -1));

        JT_service.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service ID", "Bike ID", "Date", "Mechanic"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JT_service.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JT_serviceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JT_service);

        roundPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 1220, 800));

        add(roundPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 1280, 1030));
    }// </editor-fold>//GEN-END:initComponents

    private void JT_serviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JT_serviceMouseClicked
        try {
            DefaultTableModel dtm = (DefaultTableModel) JT_service.getModel();
            int selectRow = JT_service.getSelectedRow();

            String ser_id = dtm.getValueAt(selectRow, 0).toString();
            txt_serv_id.setText(ser_id);
            String bike_id = dtm.getValueAt(selectRow, 1).toString();
            txt_bike_id.setText(bike_id);
            String date = dtm.getValueAt(selectRow, 2).toString();
            txt_date.setText(date);
            String mecha = dtm.getValueAt(selectRow, 3).toString();
            txt_mechanicID.setText(mecha);

            ResultSet rs2 = DB.search("select * from employee "
                    + "where emp_id='" + mecha + "'");
            if (rs2.next()) {
                txt_mechanic_name.setText(rs2.getString("fname")
                        + " " + rs2.getString("lname"));
            }
            
            ResultSet rs = DB.search("select * from service_invoice where service_inv_id='" + ser_id + "'");
            if (rs.next()) {
                txt_customer.setText(rs.getString("customer_id"));
                txt_amount.setText(rs.getString("nettotal"));
               
            }
             String type_id = (rs.getString("type_id"));
              ResultSet rs3 = DB.search("select * from service_type where service_id='" + type_id + "'");
            if (rs3.next()) {
                txt_service_type.setText(rs3.getString("service_name"));
              
               
            }
             
             
             
        } catch (Exception e) {
            log.error("Load Product Details Failed", e);
        }
    }//GEN-LAST:event_JT_serviceMouseClicked

    private void textFieldAnimation1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldAnimation1KeyReleased
        DefaultTableModel dtm = (DefaultTableModel) JT_service.getModel();
        String searchText = textFieldAnimation1.getText();
        TableRowSorter<DefaultTableModel> searchProduct = new TableRowSorter<>(dtm);
        JT_service.setRowSorter(searchProduct);
        searchProduct.setRowFilter(RowFilter.regexFilter(searchText));
    }//GEN-LAST:event_textFieldAnimation1KeyReleased

    private void clearFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearFieldMouseClicked
        clearFields();
    }//GEN-LAST:event_clearFieldMouseClicked

    private void clearFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearFieldMouseEntered

    }//GEN-LAST:event_clearFieldMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaswingdev.swing.table.Table JT_service;
    private javaswingdev.card.Card card1;
    private javax.swing.JLabel clearField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javaswingdev.swing.RoundPanel roundPanel1;
    private javaswingdev.swing.RoundPanel roundPanel2;
    private swing.TextFieldAnimation textFieldAnimation1;
    private javax.swing.JTextField txt_amount;
    private javax.swing.JTextField txt_bike_id;
    private javax.swing.JTextField txt_customer;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_mechanicID;
    private javax.swing.JTextField txt_mechanic_name;
    private javax.swing.JTextField txt_serv_id;
    private javax.swing.JTextField txt_service_type;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) JT_service.getModel();
            dtm.setRowCount(0);
            ResultSet rs = DB.search("select * from service_invoice order by date DESC");
            while (rs.next()) {
                Vector v = new Vector();
                v.add(rs.getString("service_inv_id"));
                v.add(rs.getString("bike_id"));
                v.add(rs.getString("date"));
                v.add(rs.getString("mechanic"));
                dtm.addRow(v);

            }

        } catch (Exception e) {
            log.error("Load Service Details Failed", e);
        }
    }

    private void clearFields() {
        txt_amount.setText(null);
        txt_bike_id.setText(null);
        txt_customer.setText(null);
        txt_date.setText(null);
        txt_mechanicID.setText(null);
        txt_mechanic_name.setText(null);
        txt_serv_id.setText(null);
        txt_service_type.setText(null);
        
        
        
        
    }
}
